services:
  - type: web
    name: gestion-livre
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn gestion_livre.wsgi:application"
    envVars:
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
